language: scala
scala:
  - 2.12.1
jdk:
  - openjdk8
branches:
  only:
  - gh-pages
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
